import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface Props {
  content: string;
  id?: string; // optional id for the preview container to target for export
}

// A simple document-style preview component that renders Markdown as a styled document.
// The component maps common Markdown elements to styled HTML elements (Tailwind classes).
// This provides a "finished document" look instead of showing raw Markdown source.
function DocumentPreview({ content, id }: Props) {
  const mdComponents: any = {
    h1: ({ node, ...props }: any) => <h1 className="text-3xl font-bold mt-2 mb-4" {...props} />,
    h2: ({ node, ...props }: any) => <h2 className="text-2xl font-semibold mt-4 mb-3" {...props} />,
    h3: ({ node, ...props }: any) => <h3 className="text-xl font-semibold mt-3 mb-2" {...props} />,
    p: ({ node, ...props }: any) => <p className="text-base leading-7 mb-3" {...props} />,
    ul: ({ node, ...props }: any) => <ul className="list-disc pl-6 mb-3" {...props} />,
    ol: ({ node, ...props }: any) => <ol className="list-decimal pl-6 mb-3" {...props} />,
    li: ({ node, ...props }: any) => <li className="mb-1" {...props} />,
    table: ({ node, ...props }: any) => <table className="min-w-full border-collapse mb-4" {...props} />,
    th: ({ node, ...props }: any) => <th className="border px-3 py-1 bg-gray-100 text-left" {...props} />,
    td: ({ node, ...props }: any) => <td className="border px-3 py-1" {...props} />,
    pre: ({ node, ...props }: any) => (
      <pre className="bg-gray-100 rounded p-3 overflow-auto text-sm" {...props} />
    ),
    code: ({ node, inline, className, ...props }: any) => (
      inline ? (
        <code className={`bg-gray-100 rounded px-1 py-0.5 text-sm ${className ?? ''}`} {...props} />
      ) : (
        <code className="block bg-gray-100 rounded p-3 overflow-auto text-sm" {...props} />
      )
    ),
  };

  return (
    <div className="document-container p-6">
      <div id={id ?? 'document-preview'} className="document-page bg-white shadow-sm p-8">
        <div className="document-header mb-6">
          <h1 className="text-2xl font-bold">Document</h1>
        </div>
        <div className="prose max-w-none dark:prose-invert">
          <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>
            {content}
          </ReactMarkdown>
        </div>
        <div className="document-footer mt-8 text-sm text-muted-foreground">
          <p>Generated by AI • Confidential</p>
        </div>
      </div>
    </div>
  );
}

export default DocumentPreview;

